include:
  - local: '.jenkins-gitlab-ci.yml'

stages:
  - verify
  - build

.trigger-jenkins-build:
  script:
    # Install jenkins python module
    - pip install python-jenkins
    # Run the script
    - chmod +x run_jenkins_job.py
    - ./run_jenkins_job.py

Pre Submit Verify:
  extends: .trigger-jenkins-build
  stage: verify
  variables:
    JENKINS_JOB_NAME: 'gitlab-triggered-based-jobs/pre-submit-test-job'
    JENKINS_PARAMETERS: '{ "DISPLAY":"From GitLab CI - Pre-submit job", "SLEEP_COUNT":"10" }'    # dictionary of jenkins job parameters
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "test" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "devops"

Post Submit Verify:
  extends: .trigger-jenkins-build
  stage: build
  variables:
    JENKINS_JOB_NAME: 'gitlab-triggered-based-jobs/post-submit-test-job'
    JENKINS_PARAMETERS: '{ "DISPLAY":"From GitLab CI - Post-submit job", "SLEEP_COUNT":"10" }'    # dictionary of jenkins job parameters
  only:
    - devops

